### ISSUE TITLE
Z-Lift not working when printing support material

### ISSUE THREAD

**Issue by jstefanop** [MatterHackers/MatterSlice#82] opened 2016-07-19 01:48 UTC
It does not seem like materslice lifts nozzle when traveling away from a support structure after a retract. This is a huge issue and I have destroyed several 20+ hour prints because of it. 

Models that I print have lots of small support structures, and if the nozzle is not lifted it either drags across the actual part leaving ugly lines on top layers, or it knocks over the delicate support structure when moving to/away from them. 

Another option would be to have a "Don't travel over printed part/support structures" option, so it forces head to move around objects when traveling from an island. This will add a little extra print time, but it will save lots of headaches.

**Comment by larsbrubaker** [comment] 2016-07-19 16:11
Thanks for the details. This is on our list and will get fixed soon.

Dupe of #70

**Closed by larsbrubaker** 2016-07-19 16:11 UTC
