### ISSUE TITLE
MatterSl

### ISSUE THREAD

**Issue by jstefanop** [MatterHackers/MatterSlice#64] opened 2016-06-24 20:09 UTC
Closely spaced inner and outer walls with <50% infill causes MatterSlice to not lay down a closed top layer, even though the model has a solid top layer. See attached STL and image for reference, and set nozzle to .4, 2 perimeter walls, .3 layer hight, and 20% infill. 

![screen shot 2016-06-24 at 4 05 44 pm](https://cloud.githubusercontent.com/assets/4368851/16349290/01581a26-3a26-11e6-9afd-f851716c1900.png)

[2x Arduino_Breadboard_Holder_v5_netfabb_mm.stl.zip](https://github.com/MatterHackers/MatterSlice/files/332503/2x.Arduino_Breadboard_Holder_v5_netfabb_mm.stl.zip)

**Comment by larsbrubaker** [comment] 2016-06-24 23:11
Good example of thin walls being required. 

Putting a reference into a bug for tracking thin walls, and closing this in favor of that.

dupe of #65

**Closed by larsbrubaker** 2016-06-24 23:11 UTC
