### ISSUE TITLE
Gcode potentially harmful to equipment

### ISSUE THREAD

**Issue by martinpirringer** [MatterHackers/MatterSlice#400] opened 2018-10-19 13:46 UTC
If you export as Gcode it should work both on an SD card and running it from Mattercontrol. This would allow to run the same Gcode days even years safely.

The problem right now:
When you save as Gcode it includes properly the bed leveling and the Z offset and will print properly from a microsd card . If you reload it in MC it will reapply the Z offset and bed leveling and now especially if you have a negative Z-offset you will engrave on your build plate. 

A fix could be a message in the comment at the beginning that says something like
;z-offset-applied: -.35
;bedleveling_applied: ..... (bed level data)

Maybe also regarding other machine info you have all kinds of info regarding the slice in the comment section.

IF MC loads the Gcode it could check for that and then take that info into consideration  with something like 
changeoffset = currentoffset - gcodeoffset ; and then apply that offset to the Z values.

**Comment by larsbrubaker** [comment] 2018-10-22 21:11
Thanks for the bug report. Marking this as a dupe of our internal bug tracking the same thing. We will address this as soon as we can.

Dupe of:
MatterHackers/MCCentral#2179
Mark exported gcode files that have leveling as such and don't apply again

**Closed by larsbrubaker** 2018-10-22 21:11 UTC
Labels: bug
